class InfraError(Exception): ...


class UserAlreadyLoggedInError(InfraError): ...


class UserLoggedOutError(InfraError): ...


class WrongPasswordError(InfraError): ...


class AuthenticationChangeError(InfraError): ...


class JWTTokenError(InfraError): ...
