# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: region.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
from google.protobuf import empty_pb2
from google.protobuf import wrappers_pb2


_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'region.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregion.proto\x12\x06region\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"3\n\x06Region\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61pital\x18\x03 \x01(\t\"-\n\x0cNewRegionDTO\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61pital\x18\x02 \x01(\t\"$\n\x0fRegionIdRequest\x12\x11\n\tregion_id\x18\x01 \x01(\t\"%\n\x10RegionIdResponse\x12\x11\n\tregion_id\x18\x01 \x01(\t\"-\n\nRegionList\x12\x1f\n\x07regions\x18\x01 \x03(\x0b\x32\x0e.region.Region2\x84\x02\n\rRegionService\x12\x38\n\nGetRegions\x12\x16.google.protobuf.Empty\x1a\x12.region.RegionList\x12\x38\n\rGetRegionById\x12\x17.region.RegionIdRequest\x1a\x0e.region.Region\x12>\n\x0c\x43reateRegion\x12\x14.region.NewRegionDTO\x1a\x18.region.RegionIdResponse\x12?\n\x0c\x44\x65leteRegion\x12\x17.region.RegionIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'region_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGION']._serialized_start=85
  _globals['_REGION']._serialized_end=136
  _globals['_NEWREGIONDTO']._serialized_start=138
  _globals['_NEWREGIONDTO']._serialized_end=183
  _globals['_REGIONIDREQUEST']._serialized_start=185
  _globals['_REGIONIDREQUEST']._serialized_end=221
  _globals['_REGIONIDRESPONSE']._serialized_start=223
  _globals['_REGIONIDRESPONSE']._serialized_end=260
  _globals['_REGIONLIST']._serialized_start=262
  _globals['_REGIONLIST']._serialized_end=307
  _globals['_REGIONSERVICE']._serialized_start=310
  _globals['_REGIONSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
