# .ruff.toml

# Включенные правила (код стиля и ошибки)
select = [
  "E",   # Ошибки pycodestyle (например, E302 — отсутствие пустой строки)
  "W",   # Предупреждения pycodestyle (например, W291 — пробелы в конце строки)
  "F",   # Ошибки pyflakes (неиспользуемые импорты, несуществующие переменные)
  "I",   # isort — сортировка импортов
  "B",   # flake8-bugbear — потенциальные баги (например, mutable defaults)
  "C4",  # flake8-comprehensions — плохие компрехеншены
  "UP",  # pyupgrade — устаревший синтаксис (например, f-строки вместо .format())
]

# Исключить слишком длинные строки (если ты используешь Black или не строгий лимит)
ignore = [
  "E501",  # Слишком длинная строка (длиннее 88 символов) — лучше убрать, если используешь форматирование
  "F811",
  "E712",
  "B904"
]

# Максимальная длина строки
line-length = 88

# Исключить папки
exclude = [
  ".venv",
  "__pycache__",
  "venv",
  "build",
  "dist",
  "*.pyc",
  "migrations",
  "node_modules"
]

# Настройка isort (сортировка импортов)
[lint.isort]
known-first-party = ["myproject"]  # ← замени "myproject" на имя твоего пакета/папки

# Форматирование кода (опционально, альтернатива Black)
[format]
line-ending = "lf"  # Используй "lf" (Unix), если на Linux/macOS, или "crlf" на Windows
indent-style = "space"
quote-style = "single"