# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.infrastructure.grpc.district.district_pb2 as district__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in district_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DistrictServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDistricts = channel.unary_unary(
                '/district.DistrictService/GetDistricts',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=district__pb2.DistrictList.FromString,
                _registered_method=True)
        self.GetDistrictsByRegionId = channel.unary_unary(
                '/district.DistrictService/GetDistrictsByRegionId',
                request_serializer=district__pb2.RegionIdRequest.SerializeToString,
                response_deserializer=district__pb2.DistrictList.FromString,
                _registered_method=True)
        self.GetDistrictById = channel.unary_unary(
                '/district.DistrictService/GetDistrictById',
                request_serializer=district__pb2.DistrictIdRequest.SerializeToString,
                response_deserializer=district__pb2.District.FromString,
                _registered_method=True)
        self.CreateDistrict = channel.unary_unary(
                '/district.DistrictService/CreateDistrict',
                request_serializer=district__pb2.NewDistrictDTO.SerializeToString,
                response_deserializer=district__pb2.DistrictIdResponse.FromString,
                _registered_method=True)
        self.DeleteDistrict = channel.unary_unary(
                '/district.DistrictService/DeleteDistrict',
                request_serializer=district__pb2.DistrictIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DistrictServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDistricts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistrictsByRegionId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistrictById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDistrict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDistrict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistrictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDistricts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistricts,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=district__pb2.DistrictList.SerializeToString,
            ),
            'GetDistrictsByRegionId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistrictsByRegionId,
                    request_deserializer=district__pb2.RegionIdRequest.FromString,
                    response_serializer=district__pb2.DistrictList.SerializeToString,
            ),
            'GetDistrictById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistrictById,
                    request_deserializer=district__pb2.DistrictIdRequest.FromString,
                    response_serializer=district__pb2.District.SerializeToString,
            ),
            'CreateDistrict': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDistrict,
                    request_deserializer=district__pb2.NewDistrictDTO.FromString,
                    response_serializer=district__pb2.DistrictIdResponse.SerializeToString,
            ),
            'DeleteDistrict': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDistrict,
                    request_deserializer=district__pb2.DistrictIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'district.DistrictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('district.DistrictService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DistrictService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDistricts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/district.DistrictService/GetDistricts',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            district__pb2.DistrictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistrictsByRegionId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/district.DistrictService/GetDistrictsByRegionId',
            district__pb2.RegionIdRequest.SerializeToString,
            district__pb2.DistrictList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistrictById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/district.DistrictService/GetDistrictById',
            district__pb2.DistrictIdRequest.SerializeToString,
            district__pb2.District.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDistrict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/district.DistrictService/CreateDistrict',
            district__pb2.NewDistrictDTO.SerializeToString,
            district__pb2.DistrictIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDistrict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/district.DistrictService/DeleteDistrict',
            district__pb2.DistrictIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
