# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: district.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'district.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64istrict.proto\x12\x08\x64istrict\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"7\n\x08\x44istrict\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tregion_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"1\n\x0eNewDistrictDTO\x12\x11\n\tregion_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"(\n\x11\x44istrictIdRequest\x12\x13\n\x0b\x64istrict_id\x18\x01 \x01(\t\"$\n\x0fRegionIdRequest\x12\x11\n\tregion_id\x18\x01 \x01(\t\"5\n\x0c\x44istrictList\x12%\n\tdistricts\x18\x01 \x03(\x0b\x32\x12.district.District\")\n\x12\x44istrictIdResponse\x12\x13\n\x0b\x64istrict_id\x18\x01 \x01(\t2\xf3\x02\n\x0f\x44istrictService\x12>\n\x0cGetDistricts\x12\x16.google.protobuf.Empty\x1a\x16.district.DistrictList\x12K\n\x16GetDistrictsByRegionId\x12\x19.district.RegionIdRequest\x1a\x16.district.DistrictList\x12\x42\n\x0fGetDistrictById\x12\x1b.district.DistrictIdRequest\x1a\x12.district.District\x12H\n\x0e\x43reateDistrict\x12\x18.district.NewDistrictDTO\x1a\x1c.district.DistrictIdResponse\x12\x45\n\x0e\x44\x65leteDistrict\x12\x1b.district.DistrictIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'district_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISTRICT']._serialized_start=89
  _globals['_DISTRICT']._serialized_end=144
  _globals['_NEWDISTRICTDTO']._serialized_start=146
  _globals['_NEWDISTRICTDTO']._serialized_end=195
  _globals['_DISTRICTIDREQUEST']._serialized_start=197
  _globals['_DISTRICTIDREQUEST']._serialized_end=237
  _globals['_REGIONIDREQUEST']._serialized_start=239
  _globals['_REGIONIDREQUEST']._serialized_end=275
  _globals['_DISTRICTLIST']._serialized_start=277
  _globals['_DISTRICTLIST']._serialized_end=330
  _globals['_DISTRICTIDRESPONSE']._serialized_start=332
  _globals['_DISTRICTIDRESPONSE']._serialized_end=373
  _globals['_DISTRICTSERVICE']._serialized_start=376
  _globals['_DISTRICTSERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
