# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: city.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'city.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncity.proto\x12\x04\x63ity\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"[\n\x04\x43ity\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64istrict_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08obj_type\x18\x04 \x01(\t\x12\x12\n\npopulation\x18\x05 \x01(\x05\"U\n\nNewCityDTO\x12\x13\n\x0b\x64istrict_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08obj_type\x18\x03 \x01(\t\x12\x12\n\npopulation\x18\x04 \x01(\x05\" \n\rCityIdRequest\x12\x0f\n\x07\x63ity_id\x18\x01 \x01(\t\"(\n\x11\x44istrictIdRequest\x12\x13\n\x0b\x64istrict_id\x18\x01 \x01(\t\"&\n\x08\x43ityList\x12\x1a\n\x06\x63ities\x18\x01 \x03(\x0b\x32\n.city.City\"!\n\x0e\x43ityIdResponse\x12\x0f\n\x07\x63ity_id\x18\x01 \x01(\t2\xa5\x02\n\x0b\x43ityService\x12\x33\n\tGetCities\x12\x16.google.protobuf.Empty\x1a\x0e.city.CityList\x12@\n\x15GetCitiesByDistrictId\x12\x17.city.DistrictIdRequest\x1a\x0e.city.CityList\x12.\n\x0bGetCityById\x12\x13.city.CityIdRequest\x1a\n.city.City\x12\x34\n\nCreateCity\x12\x10.city.NewCityDTO\x1a\x14.city.CityIdResponse\x12\x39\n\nDeleteCity\x12\x13.city.CityIdRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'city_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CITY']._serialized_start=81
  _globals['_CITY']._serialized_end=172
  _globals['_NEWCITYDTO']._serialized_start=174
  _globals['_NEWCITYDTO']._serialized_end=259
  _globals['_CITYIDREQUEST']._serialized_start=261
  _globals['_CITYIDREQUEST']._serialized_end=293
  _globals['_DISTRICTIDREQUEST']._serialized_start=295
  _globals['_DISTRICTIDREQUEST']._serialized_end=335
  _globals['_CITYLIST']._serialized_start=337
  _globals['_CITYLIST']._serialized_end=375
  _globals['_CITYIDRESPONSE']._serialized_start=377
  _globals['_CITYIDRESPONSE']._serialized_end=410
  _globals['_CITYSERVICE']._serialized_start=413
  _globals['_CITYSERVICE']._serialized_end=706
# @@protoc_insertion_point(module_scope)
