# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.infrastructure.grpc.city.city_pb2 as city__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in city_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCities = channel.unary_unary(
                '/city.CityService/GetCities',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=city__pb2.CityList.FromString,
                _registered_method=True)
        self.GetCitiesByDistrictId = channel.unary_unary(
                '/city.CityService/GetCitiesByDistrictId',
                request_serializer=city__pb2.DistrictIdRequest.SerializeToString,
                response_deserializer=city__pb2.CityList.FromString,
                _registered_method=True)
        self.GetCityById = channel.unary_unary(
                '/city.CityService/GetCityById',
                request_serializer=city__pb2.CityIdRequest.SerializeToString,
                response_deserializer=city__pb2.City.FromString,
                _registered_method=True)
        self.CreateCity = channel.unary_unary(
                '/city.CityService/CreateCity',
                request_serializer=city__pb2.NewCityDTO.SerializeToString,
                response_deserializer=city__pb2.CityIdResponse.FromString,
                _registered_method=True)
        self.DeleteCity = channel.unary_unary(
                '/city.CityService/DeleteCity',
                request_serializer=city__pb2.CityIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCitiesByDistrictId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCityById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCities,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=city__pb2.CityList.SerializeToString,
            ),
            'GetCitiesByDistrictId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCitiesByDistrictId,
                    request_deserializer=city__pb2.DistrictIdRequest.FromString,
                    response_serializer=city__pb2.CityList.SerializeToString,
            ),
            'GetCityById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCityById,
                    request_deserializer=city__pb2.CityIdRequest.FromString,
                    response_serializer=city__pb2.City.SerializeToString,
            ),
            'CreateCity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCity,
                    request_deserializer=city__pb2.NewCityDTO.FromString,
                    response_serializer=city__pb2.CityIdResponse.SerializeToString,
            ),
            'DeleteCity': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCity,
                    request_deserializer=city__pb2.CityIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'city.CityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('city.CityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/city.CityService/GetCities',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            city__pb2.CityList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCitiesByDistrictId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/city.CityService/GetCitiesByDistrictId',
            city__pb2.DistrictIdRequest.SerializeToString,
            city__pb2.CityList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCityById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/city.CityService/GetCityById',
            city__pb2.CityIdRequest.SerializeToString,
            city__pb2.City.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/city.CityService/CreateCity',
            city__pb2.NewCityDTO.SerializeToString,
            city__pb2.CityIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/city.CityService/DeleteCity',
            city__pb2.CityIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
